### ISSUE TITLE
Acceptance Criteria - Release checklist

### ISSUE THREAD

**Issue by vineeth-pappu** [vineeth-pappu/GitHub-Search-Application#7]
- [x] Cleanliness of the code
- [x] Use modern ES6+ syntax, async/await, elegant & readable code
- [x] All the edgecases have been handled
- [x] Typescript definitions, types, interfaces.
- [x] README.md file explaining your high level solution and any decisions you made and the reasons behind them
